# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userinterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(982, 760)
        MainWindow.setStyleSheet("background-color: #272735;\n"
"\n"
"MainWindow.setStyleSheet(\n"
"    \"QMainWindow { \"\n"
"    \"    background-color: #272735; \" // Example background color for the main window\n"
"    \"} \"\n"
"    \"QMessageBox { \"\n"
"    \"    background-color: #FFFFFF; \" // Override for QMessageBox specifically\n"
"    \"    color: black; \"              // Text color for the QMessageBox\n"
"    \"} \"\n"
"    \"QMessageBox QLabel { \"\n"
"    \"    color: red; \"                // Text color for labels in QMessageBox\n"
"    \"} \"\n"
"    // Add more specific styles for other QMessageBox elements if needed\n"
");\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.registerimage_2 = QtWidgets.QPushButton(self.centralwidget)
        self.registerimage_2.setGeometry(QtCore.QRect(140, 440, 331, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.registerimage_2.setFont(font)
        self.registerimage_2.setStyleSheet("QPushButton {\n"
"    background-color: #AD1457;\n"
"    color: #E9E9EA;\n"
"    /*border: 2px solid rgb(0, 140, 225);*/ \n"
"    padding: 5px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #AF3068;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #960947;\n"
"}\n"
"\n"
"")
        self.registerimage_2.setObjectName("registerimage_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 510, 215, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: #E9E9EA;\n"
"    /*border: 2px solid rgb(0, 140, 225);*/ \n"
"}\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.registerimage_3 = QtWidgets.QPushButton(self.centralwidget)
        self.registerimage_3.setGeometry(QtCore.QRect(140, 550, 331, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.registerimage_3.setFont(font)
        self.registerimage_3.setStyleSheet("QPushButton {\n"
"    background-color: #AD1457;\n"
"    color: #E9E9EA;\n"
"    /*border: 2px solid rgb(0, 140, 225);*/ \n"
"    padding: 5px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #AF3068;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #960947;\n"
"}\n"
"\n"
"")
        self.registerimage_3.setObjectName("registerimage_3")
        self.registerimage_4 = QtWidgets.QPushButton(self.centralwidget)
        self.registerimage_4.setGeometry(QtCore.QRect(140, 650, 331, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.registerimage_4.setFont(font)
        self.registerimage_4.setStyleSheet("QPushButton {\n"
"    background-color: #5445FF;\n"
"    color: #E9E9EA;\n"
"    /*border: 2px solid rgb(0, 140, 225);*/ \n"
"    padding: 5px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E51F6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4434FF;\n"
"}\n"
"\n"
"")
        self.registerimage_4.setObjectName("registerimage_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(390, 40, 215, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: #E9E9EA;\n"
"    /*border: 2px solid rgb(0, 140, 225);*/ \n"
"}\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-20, 490, 1141, 3))
        self.line.setStyleSheet("Line {\n"
"    background-color: #AD1457;\n"
"    color: #E9E9EA;\n"
"    /*border: 2px solid rgb(0, 140, 225);*/ \n"
"    padding: 5px;\n"
"    border-radius: 10px;\n"
"}\n"
"Line {\n"
"    background-color: #AD1457;\n"
"    color: #E9E9EA;\n"
"    /*border: 2px solid rgb(0, 140, 225);*/ \n"
"    padding: 5px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"Line:hover {\n"
"    background-color: #AF3068;\n"
"}\n"
"\n"
"Line:pressed {\n"
"    background-color: #960947;\n"
"}\n"
"\n"
"\n"
"")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.image3 = QtWidgets.QLabel(self.centralwidget)
        self.image3.setGeometry(QtCore.QRect(20, 80, 300, 300))
        self.image3.setStyleSheet("background-color: #39394B;")
        self.image3.setText("")
        self.image3.setObjectName("image3")
        self.fixedimage = QtWidgets.QPushButton(self.centralwidget)
        self.fixedimage.setGeometry(QtCore.QRect(20, 390, 300, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.fixedimage.setFont(font)
        self.fixedimage.setStyleSheet("QPushButton {\n"
"    background-color: #5445FF;\n"
"    color: #E9E9EA;\n"
"    /*border: 2px solid rgb(0, 140, 225);*/ \n"
"    padding: 5px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E51F6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4434FF;\n"
"}\n"
"\n"
"")
        self.fixedimage.setObjectName("fixedimage")
        self.image1 = QtWidgets.QLabel(self.centralwidget)
        self.image1.setGeometry(QtCore.QRect(340, 80, 300, 300))
        self.image1.setStyleSheet("background-color: #39394B;")
        self.image1.setText("")
        self.image1.setObjectName("image1")
        self.movingimage = QtWidgets.QPushButton(self.centralwidget)
        self.movingimage.setGeometry(QtCore.QRect(340, 390, 300, 24))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.movingimage.setFont(font)
        self.movingimage.setStyleSheet("QPushButton {\n"
"    background-color: #5445FF;\n"
"    color: #E9E9EA;\n"
"    /*border: 2px solid rgb(0, 140, 225);*/ \n"
"    padding: 5px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E51F6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4434FF;\n"
"}\n"
"\n"
"")
        self.movingimage.setObjectName("movingimage")
        self.image2 = QtWidgets.QLabel(self.centralwidget)
        self.image2.setGeometry(QtCore.QRect(660, 80, 300, 300))
        self.image2.setStyleSheet("background-color: #39394B;")
        self.image2.setText("")
        self.image2.setObjectName("image2")
        self.registerimage = QtWidgets.QPushButton(self.centralwidget)
        self.registerimage.setGeometry(QtCore.QRect(660, 390, 300, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.registerimage.setFont(font)
        self.registerimage.setStyleSheet("QPushButton {\n"
"    background-color: #5445FF;\n"
"    color: #E9E9EA;\n"
"    /*border: 2px solid rgb(0, 140, 225);*/ \n"
"    padding: 5px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5E51F6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #4434FF;\n"
"}\n"
"\n"
"")
        self.registerimage.setObjectName("registerimage")
        self.registerimage_5 = QtWidgets.QPushButton(self.centralwidget)
        self.registerimage_5.setGeometry(QtCore.QRect(140, 600, 331, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.registerimage_5.setFont(font)
        self.registerimage_5.setStyleSheet("QPushButton {\n"
"    background-color: #AD1457;\n"
"    color: #E9E9EA;\n"
"    /*border: 2px solid rgb(0, 140, 225);*/ \n"
"    padding: 5px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #AF3068;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #960947;\n"
"}\n"
"\n"
"")
        self.registerimage_5.setObjectName("registerimage_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.registerimage_2.setText(_translate("MainWindow", "Register Image"))
        self.label_2.setText(_translate("MainWindow", "Sequential Image Registration"))
        self.registerimage_3.setText(_translate("MainWindow", "Upload Folder"))
        self.registerimage_4.setText(_translate("MainWindow", "Register Folder"))
        self.label_3.setText(_translate("MainWindow", "Pairwise Image Registration"))
        self.fixedimage.setText(_translate("MainWindow", "Uploade Fixed Image"))
        self.movingimage.setText(_translate("MainWindow", "Uploade Moving Image"))
        self.registerimage.setText(_translate("MainWindow", "Download Register Image"))
        self.registerimage_5.setText(_translate("MainWindow", "Select Result Folder"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
